### ISSUE TITLE
Can't save repositories txt file after adding text?

### ISSUE THREAD

**Issue by Crom4343** [laundmo/bonelab-mod-repo#13]
After adding https://blrepo.laund.moe/repository.json it won't let me save the file, only allows me to save as outside of the quest, any ideas?

**Comment by laundmo** [comment]
did you follow the instructions to:

- copy file to desktop
- edit file and save
- copy back to quest making sure to override

properly? or are you using a quest file manager?

**Comment by Crom4343** [comment]
I have done this now and it seems to have worked, thank you so much!
