### ISSUE TITLE
Newer mods not added to the repo

### ISSUE THREAD

**Issue by Woogoo336** [laundmo/bonelab-mod-repo#17]
I noticed that mods newer than 15 days old aren't showing up in the repo. It seems like they just stopped being added after this point. The last mod I can find on the repo is https://mod.io/g/bonelab/m/test-park and anything newer does not appear.

**Comment by laundmo** [comment]
thanks for the report, i've been getting a few of them. i'll have to take a look, i dont have any clue why.

**Comment by Woogoo336** [comment]
Looks like this is happening again, last mod on the list was 22 days ago. Also on the main page 
![image](https://github.com/laundmo/bonelab-mod-repo/assets/111623368/41a25ad9-b16c-4a55-b4a0-24f3d152f78f)
