### ISSUE TITLE
Repo not updating again

### ISSUE THREAD

**Issue by Woogoo336** [laundmo/bonelab-mod-repo#21]
![image](https://github.com/laundmo/bonelab-mod-repo/assets/111623368/8d3f01c7-dec2-4cc5-96ba-12c60f35488d)
I notice the date is pretty old, and the last mod in the repo was uploaded to modio at about that time. New mods are missing from the repo.

**Comment by laundmo** [comment]
hah. you managed to make this issue like 5 minutes after i started working on it. Its fixed now, but i'm changing the homepage to include the mod.io logo. not sure if thats the reason, but the issue was a invalid api key.

**Comment by laundmo** [comment]
Its been updating for a day now
