### ISSUE TITLE
Port over Nota's quest or pcvr checker to test whther a mod on mod.io had the wrong platform assigned

### ISSUE THREAD

**Issue by laundmo** [laundmo/bonelab-mod-repo#3]
@Nota-Nom has a tool to check whether a pallet is quest or pcvr over at https://github.com/Nota-Nom/BoneLab-Tools 

This issue represents a TODO to integrate that checking code.

If you want to start work on this issue, please comment below to let me/others know.

**Comment by Nota-Nom** [comment]
Looking into it
